add builder, debug locally with act
- use go.mod for go version
- update .gitignore

Signed-off-by: Christopher Larivière <lariviere.c@gmail.com>

diff --git a/.github/workflows/builder.yaml b/.github/workflows/builder.yaml
--- a/.github/workflows/builder.yaml
+++ b/.github/workflows/builder.yaml
@@ -7,67 +7,97 @@ on:
 
 jobs:
   prepare-matrix:
-    runs-on: ubuntu-latest
+    runs-on: "ubuntu-latest"
     outputs:
-      matricies: ${{ steps.prepare-matrices.outputs.matrices }}
-    strategy:
-      matrix:
-        go: ["1.21"]
+      matrices: ${{ steps.prepare-matrices.outputs.matrices }}
     name: Go - Prepare matrices
     steps:
       - name: Checkout repository
         uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
-      
+
       - name: Setup Go
         uses: actions/setup-go@v4
         with:
-          go-version: ${{ matrix.go }}
+          go-version-file: go.mod
 
-      - name: Matricies
+      - name: Get dependencies
+        run: |
+          go mod download
+
+      - name: Matrices
         id: prepare-matrices
         shell: bash
         run: |
-          matrices=$(go run cmd/containers.go "bitwarden-cli,protonmail-bridge-docker,tf-runner-bw","true","false","stable")
+          matrices=$(go run cmd/containers.go "all" "true" "false" "stable")
+          echo "matrices=${matrices}" >> $GITHUB_OUTPUT
+          echo "${matrices}"
   build-and-push-image:
+    name: Build/Test ${{ matrix.image.name }} (${{ matrix.image.platform }})
+    needs: prepare-matrix
     runs-on: ubuntu-latest
+    if: ${{ toJSON(fromJSON(needs.prepare-matrix.outputs.matrices).imagePlatforms) != '[]' && toJSON(fromJSON(needs.prepare-matrix.outputs.matrices).imagePlatforms) != '' }}
     strategy:
       fail-fast: false
       matrix:
-        include:
-          - context: ./apps/bitwarden-cli
-            image: ghcr.io/${{ github.repository_owner }}/bitwarden-cli
-          - context: ./apps/tf-runner-bw
-            image: ghcr.io/${{ github.repository_owner }}/tf-runner-bw
-          - context: ./apps/protonmail-bridge-docker
-            image: ghcr.io/${{ github.repository_owner }}/protonmail-bridge-docker
-
+        image: ["${{ fromJSON(needs.prepare-matrix.outputs.matrices).imagePlatforms }}"]
     permissions:
       contents: read
       packages: write
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
+      - name: Log Matrix Input
+        shell: bash
+        run: |
+          cat << EOF
+          ${{ toJSON(matrix.image)}}
+          EOF
+      - name: Validate Matrix Input
+        shell: bash
+        run: |
+          if [[ -z "${{ matrix.image.name }}" ]]; then
+              echo "image.name is empty"
+              exit 1
+          fi
+          if [[ -z "${{ matrix.image.version }}" ]]; then
+              echo "image.version is empty"
+              exit 1
+          fi
+          if [[ -z "${{ matrix.image.context }}" ]]; then
+              echo "image.context is empty"
+              exit 1
+          fi
+          if [[ -z "${{ matrix.image.dockerfile }}" ]]; then
+              echo "image.dockerfile is empty"
+              exit 1
+          fi
+          if [[ -z "${{ matrix.image.platform }}" ]]; then
+              echo "image.platform is empty"
+              exit 1
+          fi
+          echo "${{ matrix.image.name }}" | grep -E "[a-zA-Z0-9_\.\-]+" || "Image Name is invalid"
+          echo "${{ matrix.image.version }}" | grep -E "[a-zA-Z0-9_\.\-]+" || "Image Version is invalid"
+      # - name: Checkout repository
+      #   uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Login to GitHub Container Registry
+      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5
-        with:
-          images: ${{ matrix.image }}
+      # - name: Docker meta
+      #   id: meta
+      #   uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5
+      #   with:
+      #     images: ${{ matrix.image }}
 
-      - name: Build and Push
-        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
-        with:
-          context: ${{ matrix.context }}
-          file: ${{ matrix.context }}/Dockerfile
-          push: ${{ github.event_name != 'pull_request' }}
-          platforms: linux/amd64
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+      # - name: Build and Push
+      #   uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
+      #   with:
+      #     context: ${{ matrix.context }}
+      #     file: ${{ matrix.dockerfile }}
+      #     push: ${{ github.event_name != 'pull_request' }}
+      #     platforms: ${{ matrix.platform }}
+      #     tags: ${{ steps.meta.outputs.tags }}
+      #     labels: ${{ steps.meta.outputs.labels }}
